### ISSUE TITLE
Missing NotifyPrefixesChangedEventArgs.

### ISSUE THREAD

**Issue by azchohfi** [paulpdaniels/MiniWamp#4]
This file is referenced but it is not available.

**Comment by paulpdaniels** [comment]
@azchohfi Thanks for the bug report! I updated it in commit b43bc6123173d8c5288e112859208aec24fa0823, and added a super minor version release as well.

**Comment by azchohfi** [comment]
Great! That's just what I ended up doing, but I didn't knew if there were any other logic inside it, so I didn't send a PR. Thanks and keep the great work!
