### ISSUE TITLE
Project can/should target Windows 8.1 AND Windows Phone 8.1

### ISSUE THREAD

**Issue by azchohfi** [paulpdaniels/MiniWamp#5]
Description is pretty strait forward. All code compile (and should work) on Windows Phone 8.1 (WinRT, not Silverlight) so the PCL should also target it. This would allow the project to be used in a Shared project between a Windows 8.1 and a Windows Phone 8.1 project.

**Comment by paulpdaniels** [comment]
@azchohfi I added a new Nuget version [0.2.0-prerelease](https://www.nuget.org/packages/MiniWamp/0.2.0-prerelease) (prerelease for now) which includes WP 8.1 and .NET 4.5 support.

Could you give that a shot? I haven't done any WP8.1 stuff with this library so I only have a minimal project to test it with.

That version includes a lot of refactorings as well so let me know if it breaks anything on your build.

**Comment by azchohfi** [comment]
Yes, this works pretty good, thanks!
