### ISSUE TITLE
There is no way to sign to any MessageWebSocketTransport's events

### ISSUE THREAD

**Issue by azchohfi** [paulpdaniels/MiniWamp#6]
Either this class is made public, or DefaultTransportFactory's Create method should be virtual.
Which one?

**Comment by paulpdaniels** [comment]
@azchohfi I don't think making `DefaultTransportFactory` a virtual method would help, you can already override it by passing in a `Func` or an `ITransportFactory` to `WampClient`.  `MessageWebSocketTransport` should be public, I'll fix and push a new release later today.

**Comment by azchohfi** [comment]
If it was a virtual method I could just create an instance of a custom DefaultTransportFactory class, overriding the create method and call the base.Create method, hooking anything I needed.

**Comment by paulpdaniels** [comment]
@azchohfi This should be fixed as of fc8fd98880716e04d169da8e10dfafe333731996 and version [0.2.4](https://www.nuget.org/packages/MiniWamp/0.2.4) can I close this issue?

**Comment by paulpdaniels** [comment]
Closing as resolved
